manifest:
  version: "0.12"
  remotes:
    - name: hardwario
      url-base: https://github.com/hardwario
  projects:
    - name: nrf
      remote: hardwario
      repo-path: ncs.git
      revision: v2.5-chester-branch
      import: true
  self:
    path: chester
    west-commands: scripts/west-commands.yml
