manifest:
  version: "0.12"
  remotes:
    - name: nordic
      url-base: https://github.com/nrfconnect
  projects:
    - name: nrf
      remote: nordic
      repo-path: sdk-nrf
      revision: v3.4-branch
      import: true
  self:
    path: chester
    west-commands: scripts/west-commands.yml
