manifest:
  version: "0.12"
  remotes:
    - name: hardwario
      url-base: https://github.com/hardwario
  projects:
    - name: nrf
      remote: hardwario
      repo-path: ncs.git
      revision: v2.5-chester-branch
      import: true
    - name: doxygen-awesome-css
      url: https://github.com/jothepro/doxygen-awesome-css
      revision: main
  self:
    path: chester
    west-commands: scripts/west-commands.yml
