#ifndef MSG_KEY_H_
#define MSG_KEY_H_

/* This file has been generated using the script gen-msg-key.py */

#ifdef __cplusplus
extern "C" {
#endif

enum msg_key {
	MSG_KEY_ACCELERATION_X = 0,
	MSG_KEY_ACCELERATION_Y = 1,
	MSG_KEY_ACCELERATION_Z = 2,
	MSG_KEY_ACCELEROMETER = 3,
	MSG_KEY_ATTRIBUTE = 4,
	MSG_KEY_BAND = 5,
	MSG_KEY_BATTERY = 6,
	MSG_KEY_CID = 7,
	MSG_KEY_CONSUMED_ENERGY = 8,
	MSG_KEY_CURRENT_LOAD = 9,
	MSG_KEY_EARFCN = 10,
	MSG_KEY_ECL = 11,
	MSG_KEY_EEST = 12,
	MSG_KEY_FRAME = 13,
	MSG_KEY_FW_NAME = 14,
	MSG_KEY_FW_VERSION = 15,
	MSG_KEY_HW_REVISION = 16,
	MSG_KEY_HW_VARIANT = 17,
	MSG_KEY_IMEI = 18,
	MSG_KEY_IMSI = 19,
	MSG_KEY_LOAD_CELL = 20,
	MSG_KEY_MOTION_COUNTER = 21,
	MSG_KEY_NETWORK = 22,
	MSG_KEY_ORIENTATION = 23,
	MSG_KEY_PARAMETER = 24,
	MSG_KEY_PASS_COUNTER_ADULT = 25,
	MSG_KEY_PASS_COUNTER_CHILD = 26,
	MSG_KEY_PEOPLE_MEASUREMENTS = 27,
	MSG_KEY_PLMN = 28,
	MSG_KEY_PRODUCT_NAME = 29,
	MSG_KEY_PROTOCOL = 30,
	MSG_KEY_RAW_RESULT_A1 = 31,
	MSG_KEY_RAW_RESULT_A2 = 32,
	MSG_KEY_RAW_RESULT_B1 = 33,
	MSG_KEY_RAW_RESULT_B2 = 34,
	MSG_KEY_RSRP = 35,
	MSG_KEY_RSRQ = 36,
	MSG_KEY_SEQUENCE = 37,
	MSG_KEY_SERIAL_NUMBER = 38,
	MSG_KEY_SNR = 39,
	MSG_KEY_STATE = 40,
	MSG_KEY_STAY_COUNTER_ADULT = 41,
	MSG_KEY_STAY_COUNTER_CHILD = 42,
	MSG_KEY_TEMPERATURE = 43,
	MSG_KEY_THERMOMETER = 44,
	MSG_KEY_TIMESTAMP = 45,
	MSG_KEY_TOTAL_TIME_ADULT = 46,
	MSG_KEY_TOTAL_TIME_CHILD = 47,
	MSG_KEY_UPTIME = 48,
	MSG_KEY_VENDOR_NAME = 49,
	MSG_KEY_VOLTAGE_LOAD = 50,
	MSG_KEY_VOLTAGE_REST = 51,
	MSG_KEY_WEIGHT_MEASUREMENTS = 52,
};

#ifdef __cplusplus
}
#endif

#endif /* MSG_KEY_H_ */
