/*
 * Copyright (c) 2023 HARDWARIO a.s.
 *
 * SPDX-License-Identifier: LicenseRef-HARDWARIO-5-Clause
 */

#ifndef MSG_KEY_H_
#define MSG_KEY_H_

/* This file has been generated using the script gen-msg-key.py */

#ifdef __cplusplus
extern "C" {
#endif

enum msg_key {
	MSG_KEY_ACCELERATION_X = 0,
	MSG_KEY_ACCELERATION_Y = 1,
	MSG_KEY_ACCELERATION_Z = 2,
	MSG_KEY_ACCELEROMETER = 3,
	MSG_KEY_ATTRIBUTE = 4,
	MSG_KEY_BAND = 5,
	MSG_KEY_BATTERY = 6,
	MSG_KEY_CID = 7,
	MSG_KEY_CONSUMED_ENERGY = 8,
	MSG_KEY_CURRENT_LOAD = 9,
	MSG_KEY_EARFCN = 10,
	MSG_KEY_ECL = 11,
	MSG_KEY_EEST = 12,
	MSG_KEY_FRAME = 13,
	MSG_KEY_FW_NAME = 14,
	MSG_KEY_FW_VERSION = 15,
	MSG_KEY_HW_REVISION = 16,
	MSG_KEY_HW_VARIANT = 17,
	MSG_KEY_IMEI = 18,
	MSG_KEY_IMSI = 19,
	MSG_KEY_LOAD_CELL = 20,
	MSG_KEY_NETWORK = 21,
	MSG_KEY_ORIENTATION = 22,
	MSG_KEY_PARAMETER = 23,
	MSG_KEY_PEOPLE_MEASUREMENTS = 24,
	MSG_KEY_PLMN = 25,
	MSG_KEY_PRODUCT_NAME = 26,
	MSG_KEY_PROTOCOL = 27,
	MSG_KEY_RSRP = 28,
	MSG_KEY_RSRQ = 29,
	MSG_KEY_SEQUENCE = 30,
	MSG_KEY_SERIAL_NUMBER = 31,
	MSG_KEY_SNR = 32,
	MSG_KEY_STATE = 33,
	MSG_KEY_TEMPERATURE = 34,
	MSG_KEY_THERMOMETER = 35,
	MSG_KEY_TIMESTAMP = 36,
	MSG_KEY_UPTIME = 37,
	MSG_KEY_VENDOR_NAME = 38,
	MSG_KEY_VOLTAGE_LOAD = 39,
	MSG_KEY_VOLTAGE_REST = 40,
	MSG_KEY_WEIGHT_MEASUREMENTS = 41,
};

#ifdef __cplusplus
}
#endif

#endif /* MSG_KEY_H_ */
