version: 1
variants:
- name: CHESTER Current
  fw_bundle: com.hardwario.chester.app.current
  fw_name: hio-chester-current
  fw_version: v3.0.0
- name: CHESTER Current Z
  fw_bundle: com.hardwario.chester.app.current.z
  fw_name: hio-chester-current-z
  fw_version: v3.0.0
  features:
  - hardware-chester-z
  remark: Support for CHESTER-Z
- name: CHESTER Current 1W
  fw_bundle: com.hardwario.chester.app.current.1w
  fw_name: hio-chester-current-1w
  fw_version: v3.0.0
  features:
  - subsystem-ds18b20
  remark: Support for 1-Wire
project:
  variant: Current
  company: 2024 HARDWARIO a.s.
  license: 'SPDX-License-Identifier: LicenseRef-HARDWARIO-5-Clause'
  fw_name: CHESTER Current
  fw_bundle: com.hardwario.chester.app.current
  fw_version: v3.0.0
features:
- subsystem-accel
- subsystem-batt
- subsystem-button
- subsystem-bluetooth
- subsystem-ble-tag
- subsystem-bt-observer
- subsystem-bt-filter-accept-list
- subsystem-buf
- subsystem-config
- subsystem-defaults
- subsystem-info
- subsystem-led
- subsystem-log
- subsystem-rtc
- subsystem-shell
- subsystem-therm
- subsystem-wdog
- subsystem-tinycrypt
- subsystem-tinycrypt-sha256
- subsystem-zcbor
- subsystem-lte-v2
- subsystem-lrw
- subsystem-cloud
- hardware-chester-k1
#- subsystem-ds18b20
#- hardware-chester-z
parameters:
- name: interval-report
  type: int
  min: 30
  max: 86400
  default: 900
  help: 'Get/Set report interval in seconds'
- name: interval-poll
  type: int
  min: 0
  max: 86400
  default: 0
  help: 'Get/Set poll interval in seconds'
- name: event-report-delay
  type: int
  min: 1
  max: 86400
  default: 1
  help: 'Get/Set event report delay in seconds'
  depends_on: defined(FEATURE_HARDWARE_CHESTER_Z)
- name: event-report-rate
  type: int
  min: 1
  max: 3600
  default: 30
  help: 'Get/Set event report rate in reports per hour'
  depends_on: defined(FEATURE_HARDWARE_CHESTER_Z)
- name: backup-report-connected
  type: bool
  default: true
  help: 'Get/Set report when backup is active'
  depends_on: defined(FEATURE_HARDWARE_CHESTER_Z)
- name: backup-report-disconnected
  type: bool
  default: true
  help: 'Get/Set report when backup is inactive'
  depends_on: defined(FEATURE_HARDWARE_CHESTER_Z)
- name: channel-interval-sample
  type: int
  min: 1
  max: 86400
  default: 60
  help: 'Get/Set sample interval in seconds'
  depends_on: defined(FEATURE_HARDWARE_CHESTER_K1)
- name: channel-interval-aggreg
  type: int
  min: 1
  max: 86400
  default: 300
  help: 'Get/Set aggregate interval in seconds'
  depends_on: defined(FEATURE_HARDWARE_CHESTER_K1)
- name: channel-active
  type: array[bool]
  len: 4
  default: null
  help: 'Get/Set channel activation'
  depends_on: defined(FEATURE_HARDWARE_CHESTER_K1)
- name: channel-differential
  type: array[bool]
  len: 4
  default: null
  help: 'Get/Set channel differential mode'
  depends_on: defined(FEATURE_HARDWARE_CHESTER_K1)
- name: channel-calib-x0
  type: array[int]
  len: 4
  min: 30
  max: 86400
  default: null
  help: 'Get/Set channel X0 calibration point'
  depends_on: defined(FEATURE_HARDWARE_CHESTER_K1)
- name: channel-calib-x1
  type: array[int]
  len: 4
  min: 30
  max: 86400
  default: null
  help: 'Get/Set channel X1 calibration point'
  depends_on: defined(FEATURE_HARDWARE_CHESTER_K1)
- name: channel-calib-y0
  type: array[int]
  len: 4
  min: 30
  max: 86400
  default: null
  help: 'Get/Set channel Y0 calibration point'
  depends_on: defined(FEATURE_HARDWARE_CHESTER_K1)
- name: channel-calib-y1
  type: array[int]
  len: 4
  min: 30
  max: 86400
  default: null
  help: 'Get/Set channel Y1 calibration point'
  depends_on: defined(FEATURE_HARDWARE_CHESTER_K1)
- name: w1-therm-interval-sample
  type: int
  min: 1
  max: 86400
  default: 60
  help: 'Get/Set report when hygro high temperature alarm is crossed'
  depends_on: defined(FEATURE_SUBSYSTEM_DS18B20)
- name: w1-therm-interval-aggreg
  type: int
  min: 1
  max: 86400
  default: 300
  help: 'Get/Set report when hygro low temperature alarm is crossed'
  depends_on: defined(FEATURE_SUBSYSTEM_DS18B20)
commands:
- name: sample
  callback: app_work_sample()
  help: 'Sample immediately.'
- name: send
  callback: app_work_send()
  help: 'Send data immediately.'
- name: aggreg
  callback: app_work_aggreg()
  help: 'Aggregate data immediately'
extras:
- CONFIG_ADC_TLA2021_INIT_PRIORITY=60
- CONFIG_ADC_NRFX_SAADC=n
- CONFIG_ADC_SHELL=n
- CONFIG_NEWLIB_LIBC_NANO=n
