#ifndef MSG_KEY_H_
#define MSG_KEY_H_

/* This file has been generated using the script gen-msg-key.py */

#ifdef __cplusplus
extern "C" {
#endif

enum msg_key {
	MSG_KEY_ACCELERATION_X = 0,
	MSG_KEY_ACCELERATION_Y = 1,
	MSG_KEY_ACCELERATION_Z = 2,
	MSG_KEY_ACCELEROMETER = 3,
	MSG_KEY_ATTRIBUTE = 4,
	MSG_KEY_BAND = 5,
	MSG_KEY_BATTERY = 6,
	MSG_KEY_CID = 7,
	MSG_KEY_CURRENT_LOAD = 8,
	MSG_KEY_EARFCN = 9,
	MSG_KEY_ECL = 10,
	MSG_KEY_EEST = 11,
	MSG_KEY_FRAME = 12,
	MSG_KEY_FW_VERSION = 13,
	MSG_KEY_HW_REVISION = 14,
	MSG_KEY_HW_VARIANT = 15,
	MSG_KEY_IMEI = 16,
	MSG_KEY_IMSI = 17,
	MSG_KEY_MEASUREMENTS = 18,
	MSG_KEY_NETWORK = 19,
	MSG_KEY_ORIENTATION = 20,
	MSG_KEY_PARAMETER = 21,
	MSG_KEY_PLMN = 22,
	MSG_KEY_PRODUCT_NAME = 23,
	MSG_KEY_PROTOCOL = 24,
	MSG_KEY_RSRP = 25,
	MSG_KEY_RSRQ = 26,
	MSG_KEY_SEQUENCE = 27,
	MSG_KEY_SERIAL_NUMBER = 28,
	MSG_KEY_SNR = 29,
	MSG_KEY_STATE = 30,
	MSG_KEY_TEMPERATURE = 31,
	MSG_KEY_THERMOMETER = 32,
	MSG_KEY_TIMESTAMP = 33,
	MSG_KEY_UPTIME = 34,
	MSG_KEY_VENDOR_NAME = 35,
	MSG_KEY_VOLTAGE_LOAD = 36,
	MSG_KEY_VOLTAGE_REST = 37,
};

#ifdef __cplusplus
}
#endif

#endif /* MSG_KEY_H_ */
