CONFIG_CTR_DEFAULTS=y
CONFIG_CTR_LOG=y
CONFIG_CTR_SHELL=y

CONFIG_CBPRINTF_FP_SUPPORT=y

CONFIG_SENSOR=y
CONFIG_I2C=y
CONFIG_I2C_LOG_LEVEL_DBG=y
CONFIG_GPIO=y
CONFIG_ADXL355=y
CONFIG_ADXL355_TRIGGER=y
CONFIG_ADXL355_TRIGGER_GLOBAL_THREAD=y
CONFIG_ADXL355_INT1_DRDY=y
CONFIG_ADXL355_INT1_FIFO_FULL=y
#CONFIG_ADXL355_INT1_FIFO_FULL=y
#CONFIG_ADXL355_FIFO=y
#CONFIG_ADXL355_FIFO_SAMPLES=84
CONFIG_ADXL355_LOG_LEVEL_DBG=y