/*
 * Copyright (c) 2023 HARDWARIO a.s.
 *
 * SPDX-License-Identifier: LicenseRef-HARDWARIO-5-Clause
 */

#ifndef MSG_KEY_H_
#define MSG_KEY_H_

/* This file has been generated using the script gen-msg-key.py */

#ifdef __cplusplus
extern "C" {
#endif

enum msg_key {
	MSG_KEY_ACCELERATION_X = 0,
	MSG_KEY_ACCELERATION_Y = 1,
	MSG_KEY_ACCELERATION_Z = 2,
	MSG_KEY_ACCELEROMETER = 3,
	MSG_KEY_ATTRIBUTE = 4,
	MSG_KEY_BAND = 5,
	MSG_KEY_CID = 6,
	MSG_KEY_CURRENT_LOAD = 7,
	MSG_KEY_EARFCN = 8,
	MSG_KEY_ECL = 9,
	MSG_KEY_EEST = 10,
	MSG_KEY_MESSAGE = 11,
	MSG_KEY_FW_NAME = 12,
	MSG_KEY_FW_VERSION = 13,
	MSG_KEY_HW_REVISION = 14,
	MSG_KEY_HW_VARIANT = 15,
	MSG_KEY_VERSION = 16,
	MSG_KEY_IMEI = 17,
	MSG_KEY_IMSI = 18,
	MSG_KEY_NETWORK = 19,
	MSG_KEY_ORIENTATION = 20,
	MSG_KEY_PARAMETER = 21,
	MSG_KEY_PLMN = 22,
	MSG_KEY_PRODUCT_NAME = 23,
	MSG_KEY_RSRP = 24,
	MSG_KEY_RSRQ = 25,
	MSG_KEY_SEQUENCE = 26,
	MSG_KEY_SERIAL_NUMBER = 27,
	MSG_KEY_SNR = 28,
	MSG_KEY_TEMPERATURE = 29,
	MSG_KEY_THERMOMETER = 30,
	MSG_KEY_TIMESTAMP = 31,
	MSG_KEY_UPTIME = 32,
	MSG_KEY_VENDOR_NAME = 33,
	MSG_KEY_VOLTAGE_LOAD = 34,
	MSG_KEY_VOLTAGE_REST = 35,
	MSG_KEY_W1_THERMOMETERS = 36,
	MSG_KEY_MEASUREMENTS_DIV = 37,
	MSG_KEY_CHANNEL = 38,
	MSG_KEY_ANALOG_CHANNELS = 39,
	MSG_KEY_MEASUREMENTS_ANALOG_CHANNELS = 40,
	MSG_KEY_BACKUP_STATE = 41,
	MSG_KEY_LINE_VOLTAGE = 42,
	MSG_KEY_BATT_VOLTAGE = 43,
	MSG_KEY_BACKUP = 44,
	MSG_KEY_BACKUP_EVENTS = 45,
	MSG_KEY_SYSTEM = 46,
};

#ifdef __cplusplus
}
#endif

#endif /* MSG_KEY_H_ */
