/*
 * Copyright (c) 2023 HARDWARIO a.s.
 *
 * SPDX-License-Identifier: LicenseRef-HARDWARIO-5-Clause
 */

#ifndef MSG_KEY_H_
#define MSG_KEY_H_

/* This file has been generated using the script gen-msg-key.py */

#ifdef __cplusplus
extern "C" {
#endif

enum msg_key {
	MSG_KEY_ACCELERATION_X = 0,
	MSG_KEY_ACCELERATION_Y = 1,
	MSG_KEY_ACCELERATION_Z = 2,
	MSG_KEY_ACCELEROMETER = 3,
	MSG_KEY_ATTRIBUTE = 4,
	MSG_KEY_BAND = 5,
	MSG_KEY_BACKUP = 6,
	MSG_KEY_LINE_VOLTAGE = 7,
	MSG_KEY_BATT_VOLTAGE = 8,
	MSG_KEY_BACKUP_STATE = 9,
	MSG_KEY_BACKUP_EVENTS = 10,
	MSG_KEY_CID = 11,
	MSG_KEY_CURRENT_LOAD = 12,
	MSG_KEY_DISTANCE = 13,
	MSG_KEY_EARFCN = 14,
	MSG_KEY_ECL = 15,
	MSG_KEY_EEST = 16,
	MSG_KEY_MESSAGE = 17,
	MSG_KEY_MEASUREMENTS_DIV3 = 18,
	MSG_KEY_MEASUREMENTS_DIV2 = 19,
	MSG_KEY_FW_NAME = 20,
	MSG_KEY_FW_VERSION = 21,
	MSG_KEY_HW_REVISION = 22,
	MSG_KEY_HW_VARIANT = 23,
	MSG_KEY_VERSION = 24,
	MSG_KEY_HUMIDITY = 25,
	MSG_KEY_IMEI = 26,
	MSG_KEY_IMSI = 27,
	MSG_KEY_NETWORK = 28,
	MSG_KEY_HYGROMETER = 29,
	MSG_KEY_ORIENTATION = 30,
	MSG_KEY_PARAMETER = 31,
	MSG_KEY_PLMN = 32,
	MSG_KEY_PRODUCT_NAME = 33,
	MSG_KEY_RSRP = 34,
	MSG_KEY_RSRQ = 35,
	MSG_KEY_SEQUENCE = 36,
	MSG_KEY_SERIAL_NUMBER = 37,
	MSG_KEY_SNR = 38,
	MSG_KEY_ULTRASONIC_RANGER = 39,
	MSG_KEY_SYSTEM = 40,
	MSG_KEY_TEMPERATURE = 41,
	MSG_KEY_THERMOMETER = 42,
	MSG_KEY_TIMESTAMP = 43,
	MSG_KEY_UPTIME = 44,
	MSG_KEY_VENDOR_NAME = 45,
	MSG_KEY_VOLTAGE_LOAD = 46,
	MSG_KEY_VOLTAGE_REST = 47,
	MSG_KEY_W1_THERMOMETERS = 48,
	MSG_KEY_HYGRO_EVENTS = 49,
};

#ifdef __cplusplus
}
#endif

#endif /* MSG_KEY_H_ */
