#ifndef MSG_KEY_H_
#define MSG_KEY_H_

/* This file has been generated using the script gen-msg-key.py */

#ifdef __cplusplus
extern "C" {
#endif

enum msg_key {
	MSG_KEY_ACCELERATION_X = 0,
	MSG_KEY_ACCELERATION_Y = 1,
	MSG_KEY_ACCELERATION_Z = 2,
	MSG_KEY_ACCELEROMETER = 3,
	MSG_KEY_ATTRIBUTE = 4,
	MSG_KEY_BACKUP = 5,
	MSG_KEY_BAND = 6,
	MSG_KEY_BATTERY = 7,
	MSG_KEY_BUTTON = 8,
	MSG_KEY_BUTTON_X_CLICK_EVENT = 9,
	MSG_KEY_BUTTON_X_CLICK_COUNT = 10,
	MSG_KEY_BUTTON_X_HOLD_EVENT = 11,
	MSG_KEY_BUTTON_X_HOLD_COUNT = 12,
	MSG_KEY_BUTTON_1_CLICK_EVENT = 13,
	MSG_KEY_BUTTON_1_CLICK_COUNT = 14,
	MSG_KEY_BUTTON_1_HOLD_EVENT = 15,
	MSG_KEY_BUTTON_1_HOLD_COUNT = 16,
	MSG_KEY_BUTTON_2_CLICK_EVENT = 17,
	MSG_KEY_BUTTON_2_CLICK_COUNT = 18,
	MSG_KEY_BUTTON_2_HOLD_EVENT = 19,
	MSG_KEY_BUTTON_2_HOLD_COUNT = 20,
	MSG_KEY_BUTTON_3_CLICK_EVENT = 21,
	MSG_KEY_BUTTON_3_CLICK_COUNT = 22,
	MSG_KEY_BUTTON_3_HOLD_EVENT = 23,
	MSG_KEY_BUTTON_3_HOLD_COUNT = 24,
	MSG_KEY_BUTTON_4_CLICK_EVENT = 25,
	MSG_KEY_BUTTON_4_CLICK_COUNT = 26,
	MSG_KEY_BUTTON_4_HOLD_EVENT = 27,
	MSG_KEY_BUTTON_4_HOLD_COUNT = 28,
	MSG_KEY_CID = 29,
	MSG_KEY_CURRENT_LOAD = 30,
	MSG_KEY_EARFCN = 31,
	MSG_KEY_ECL = 32,
	MSG_KEY_EEST = 33,
	MSG_KEY_FRAME = 34,
	MSG_KEY_FW_VERSION = 35,
	MSG_KEY_HW_REVISION = 36,
	MSG_KEY_HW_VARIANT = 37,
	MSG_KEY_IMEI = 38,
	MSG_KEY_IMSI = 39,
	MSG_KEY_LINE = 40,
	MSG_KEY_NETWORK = 41,
	MSG_KEY_ORIENTATION = 42,
	MSG_KEY_PARAMETER = 43,
	MSG_KEY_PLMN = 44,
	MSG_KEY_PRESENT = 45,
	MSG_KEY_PRODUCT_NAME = 46,
	MSG_KEY_PROTOCOL = 47,
	MSG_KEY_RSRP = 48,
	MSG_KEY_RSRQ = 49,
	MSG_KEY_SEQUENCE = 50,
	MSG_KEY_SERIAL_NUMBER = 51,
	MSG_KEY_SNR = 52,
	MSG_KEY_STATE = 53,
	MSG_KEY_TEMPERATURE = 54,
	MSG_KEY_THERMOMETER = 55,
	MSG_KEY_TIMESTAMP = 56,
	MSG_KEY_UPTIME = 57,
	MSG_KEY_VENDOR_NAME = 58,
	MSG_KEY_VOLTAGE = 59,
	MSG_KEY_VOLTAGE_LOAD = 60,
	MSG_KEY_VOLTAGE_REST = 61,
};

#ifdef __cplusplus
}
#endif

#endif /* MSG_KEY_H_ */
