/*
 * Copyright (c) 2023 HARDWARIO a.s.
 *
 * SPDX-License-Identifier: LicenseRef-HARDWARIO-5-Clause
 */

#ifndef MSG_KEY_H_
#define MSG_KEY_H_

/* This file has been generated using the script gen-msg-key.py */

#ifdef __cplusplus
extern "C" {
#endif

enum msg_key {
	MSG_KEY_ACCELERATION_X = 0,
	MSG_KEY_ACCELERATION_Y = 1,
	MSG_KEY_ACCELERATION_Z = 2,
	MSG_KEY_ACCELEROMETER = 3,
	MSG_KEY_ATTRIBUTE = 4,
	MSG_KEY_BACKUP = 5,
	MSG_KEY_BAND = 6,
	MSG_KEY_SYSTEM = 7,
	MSG_KEY_BATTERY = 8,
	MSG_KEY_BUTTON = 9,
	MSG_KEY_CID = 10,
	MSG_KEY_CURRENT_LOAD = 11,
	MSG_KEY_EARFCN = 12,
	MSG_KEY_ECL = 13,
	MSG_KEY_EEST = 14,
	MSG_KEY_FRAME = 15,
	MSG_KEY_MESSAGE = 16,
	MSG_KEY_FW_NAME = 17,
	MSG_KEY_FW_VERSION = 18,
	MSG_KEY_HW_REVISION = 19,
	MSG_KEY_HW_VARIANT = 20,
	MSG_KEY_IMEI = 21,
	MSG_KEY_IMSI = 22,
	MSG_KEY_LINE = 23,
	MSG_KEY_NETWORK = 24,
	MSG_KEY_ORIENTATION = 25,
	MSG_KEY_PARAMETER = 26,
	MSG_KEY_PLMN = 27,
	MSG_KEY_PRESENT = 28,
	MSG_KEY_PRODUCT_NAME = 29,
	MSG_KEY_PROTOCOL = 30,
	MSG_KEY_VERSION = 31,
	MSG_KEY_RSRP = 32,
	MSG_KEY_RSRQ = 33,
	MSG_KEY_SEQUENCE = 34,
	MSG_KEY_SERIAL_NUMBER = 35,
	MSG_KEY_SNR = 36,
	MSG_KEY_STATE = 37,
	MSG_KEY_TEMPERATURE = 38,
	MSG_KEY_THERMOMETER = 39,
	MSG_KEY_TIMESTAMP = 40,
	MSG_KEY_UPTIME = 41,
	MSG_KEY_VENDOR_NAME = 42,
	MSG_KEY_LINE_VOLTAGE = 43,
	MSG_KEY_BATT_VOLTAGE = 44,
	MSG_KEY_VOLTAGE = 45,
	MSG_KEY_VOLTAGE_LOAD = 46,
	MSG_KEY_VOLTAGE_REST = 47,
	MSG_KEY_BACKUP_STATE = 48,
	MSG_KEY_BACKUP_EVENTS = 49,
	MSG_KEY_BUTTON_EVENTS = 50,
	MSG_KEY_BUTTON_X = 51,
	MSG_KEY_BUTTON_1 = 52,
	MSG_KEY_BUTTON_2 = 53,
	MSG_KEY_BUTTON_3 = 54,
	MSG_KEY_BUTTON_4 = 55,
	MSG_KEY_COUNT_CLICK = 56,
	MSG_KEY_COUNT_HOLD = 57,
};

#ifdef __cplusplus
}
#endif

#endif /* MSG_KEY_H_ */
