version: 1
variants:
- name: CHESTER Range
  fw_bundle: com.hardwario.chester.app.range
  fw_name: hio-chester-range
  fw_version: v3.0.0
- name: CHESTER Range Z
  fw_bundle: com.hardwario.chester.app.range.z
  fw_name: hio-chester-range-z
  fw_version: v3.0.0
  features:
  - hardware-chester-z
  remark: Support for CHESTER-Z
project:
  variant: Range
  company: 2024 HARDWARIO a.s.
  license: 'SPDX-License-Identifier: LicenseRef-HARDWARIO-5-Clause'
  fw_name: CHESTER Range
  fw_bundle: com.hardwario.chester.app.range
  fw_version: v3.0.0
features:
- subsystem-accel
- subsystem-batt
- subsystem-bluetooth
- subsystem-ble-tag
- subsystem-bt-filter-accept-list
- subsystem-bt-observer
- subsystem-buf
- subsystem-button
- subsystem-defaults
- subsystem-info
- subsystem-led
- subsystem-log
- subsystem-rtc
- subsystem-shell
- subsystem-therm
- subsystem-wdog
- subsystem-tinycrypt-sha256
- subsystem-tinycrypt
- subsystem-zcbor
- subsystem-lte-v2
- subsystem-cloud
- subsystem-ds18b20
- hardware-chester-mb7066-a
- chester-app-report-jitter
#- hardware-chester-mb7066-b
#- hardware-chester-s2
#- hardware-chester-z
parameters:
- name: interval-sample
  type: int
  min: 1
  max: 86400
  default: 60
  help: 'Get/Set sample interval in seconds'
- name: interval-aggreg
  type: int
  min: 1
  max: 86400
  default: 300
  help: 'Get/Set aggregate interval in seconds '
- name: interval-report
  type: int
  min: 30
  max: 86400
  default: 1800
  help: 'Get/Set report interval in seconds'
- name: interval-poll
  type: int
  min: 0
  max: 86400
  default: 0
  help: 'Get/Set polling interval in seconds'
- name: event-report-delay
  type: int
  min: 1
  max: 86400
  default: 1
  help: 'Get/Set event report delay in seconds'
  depends_on:  defined(FEATURE_HARDWARE_CHESTER_S2) || defined(FEATURE_HARDWARE_CHESTER_Z)
- name: event-report-rate
  type: int
  min: 1
  max: 3600
  default: 30
  help: 'Get/Set event report rate in reports per hour'
  depends_on: defined(FEATURE_HARDWARE_CHESTER_S2) || defined(FEATURE_HARDWARE_CHESTER_Z)
- name: backup-report-connected
  type: bool
  default: true
  help: 'Get/Set report when backup is active'
  depends_on: defined(FEATURE_HARDWARE_CHESTER_Z)
- name: backup-report-disconnected
  type: bool
  default: true
  help: 'Get/Set report when backup is inactive'
  depends_on: defined(FEATURE_HARDWARE_CHESTER_Z)
- name: hygro-t-alarm-hi-report
  type: bool
  default: false
  help: 'Get/Set report when hygro high temperature alarm is crossed'
  depends_on: defined(FEATURE_HARDWARE_CHESTER_S2)
- name: hygro-t-alarm-lo-report
  type: bool
  default: false
  help: 'Get/Set report when hygro low temperature alarm is crossed'
  depends_on: defined(FEATURE_HARDWARE_CHESTER_S2)
- name: hygro-t-alarm-hi-thr
  type: float
  min: -40.0
  max: 125.0
  default: 0.0
  help: 'Get/Set hygro high temperature alarm threshold'
  depends_on: defined(FEATURE_HARDWARE_CHESTER_S2)
- name: hygro-t-alarm-hi-hst
  type: float
  min: 0.0
  max: 100.0
  default: 0.0
  help: 'Get/Set hygro high temperature alarm hysteresis'
  depends_on: defined(FEATURE_HARDWARE_CHESTER_S2)
- name: hygro-t-alarm-lo-thr
  type: float
  min: -40.0
  max: 125.0
  default: 0.0
  help: 'Get/Set hygro low temperature alarm threshold'
  depends_on: defined(FEATURE_HARDWARE_CHESTER_S2)
- name: hygro-t-alarm-lo-hst
  type: float
  min: 0.0
  max: 100.0
  default: 0.0
  help: 'Get/Set hygro low temperature alarm hysteresis'
  depends_on: defined(FEATURE_HARDWARE_CHESTER_S2)
commands:
- name: sample
  callback: app_work_sample()
  help: 'Sample immediately.'
- name: send
  callback: app_work_send()
  help: 'Send data immediately.'
- name: aggreg
  callback: app_work_aggreg()
  help: 'Aggregate data immediately'
extras:
- CONFIG_ADC_TLA2021_INIT_PRIORITY=60

