#ifndef MSG_KEY_H_
#define MSG_KEY_H_

/* This file has been generated using the script gen-msg-key.py */

#ifdef __cplusplus
extern "C" {
#endif

enum msg_key {
	MSG_KEY_ACCEL_X = 0,
	MSG_KEY_ACCEL_Y = 1,
	MSG_KEY_ACCEL_Z = 2,
	MSG_KEY_ACCELEROMETER = 3,
	MSG_KEY_ATTRIBUTE = 4,
	MSG_KEY_BAND = 5,
	MSG_KEY_BATTERY = 6,
	MSG_KEY_CID = 7,
	MSG_KEY_CURRENT_LOAD = 8,
	MSG_KEY_EARFCN = 9,
	MSG_KEY_ECL = 10,
	MSG_KEY_EEST = 11,
	MSG_KEY_FRAME = 12,
	MSG_KEY_FW_VERSION = 13,
	MSG_KEY_HW_REVISION = 14,
	MSG_KEY_HW_VARIANT = 15,
	MSG_KEY_IMEI = 16,
	MSG_KEY_IMSI = 17,
	MSG_KEY_NETWORK = 18,
	MSG_KEY_ORIENTATION = 19,
	MSG_KEY_PARAMETER = 20,
	MSG_KEY_PLMN = 21,
	MSG_KEY_PRODUCT_NAME = 22,
	MSG_KEY_PROTOCOL = 23,
	MSG_KEY_RSRP = 24,
	MSG_KEY_RSRQ = 25,
	MSG_KEY_SAMPLE_COUNT = 26,
	MSG_KEY_SEQUENCE = 27,
	MSG_KEY_SERIAL_NUMBER = 28,
	MSG_KEY_SNR = 29,
	MSG_KEY_STATE = 30,
	MSG_KEY_TEMPERATURE_AVG = 31,
	MSG_KEY_TEMPERATURE_MAX = 32,
	MSG_KEY_TEMPERATURE_MDN = 33,
	MSG_KEY_TEMPERATURE_MIN = 34,
	MSG_KEY_TEMPERATURE = 35,
	MSG_KEY_THERMOMETER = 36,
	MSG_KEY_TIMESTAMP = 37,
	MSG_KEY_UPTIME = 38,
	MSG_KEY_VENDOR_NAME = 39,
	MSG_KEY_VOLTAGE_LOAD = 40,
	MSG_KEY_VOLTAGE_REST = 41,
	MSG_KEY_W1_THERMOMETERS = 42,
};

#ifdef __cplusplus
}
#endif

#endif /* MSG_KEY_H_ */
