/*
 * Copyright (c) 2023 HARDWARIO a.s.
 *
 * SPDX-License-Identifier: LicenseRef-HARDWARIO-5-Clause
 */

#ifndef MSG_KEY_H_
#define MSG_KEY_H_

/* This file has been generated using the script gen-msg-key.py */

#ifdef __cplusplus
extern "C" {
#endif

enum msg_key {
	MSG_KEY_ACCELERATION_X = 0,
	MSG_KEY_ACCELERATION_Y = 1,
	MSG_KEY_ACCELERATION_Z = 2,
	MSG_KEY_ACCELEROMETER = 3,
	MSG_KEY_ALTITUDE = 4,
	MSG_KEY_ATTRIBUTE = 5,
	MSG_KEY_BAND = 6,
	MSG_KEY_CID = 7,
	MSG_KEY_CO2_CONC = 8,
	MSG_KEY_CURRENT_LOAD = 9,
	MSG_KEY_EARFCN = 10,
	MSG_KEY_ECL = 11,
	MSG_KEY_EEST = 12,
	MSG_KEY_MESSAGE = 13,
	MSG_KEY_FW_NAME = 14,
	MSG_KEY_FW_VERSION = 15,
	MSG_KEY_HUMIDITY = 16,
	MSG_KEY_HYGROMETER = 17,
	MSG_KEY_HW_REVISION = 18,
	MSG_KEY_HW_VARIANT = 19,
	MSG_KEY_VERSION = 20,
	MSG_KEY_IAQ_SENSOR = 21,
	MSG_KEY_ILLUMINANCE = 22,
	MSG_KEY_IMEI = 23,
	MSG_KEY_IMSI = 24,
	MSG_KEY_MOTION_COUNT = 25,
	MSG_KEY_NETWORK = 26,
	MSG_KEY_ORIENTATION = 27,
	MSG_KEY_PARAMETER = 28,
	MSG_KEY_PLMN = 29,
	MSG_KEY_PRESS_COUNT = 30,
	MSG_KEY_PRESSURE = 31,
	MSG_KEY_PRODUCT_NAME = 32,
	MSG_KEY_RSRP = 33,
	MSG_KEY_RSRQ = 34,
	MSG_KEY_SEQUENCE = 35,
	MSG_KEY_SERIAL_NUMBER = 36,
	MSG_KEY_SNR = 37,
	MSG_KEY_TEMPERATURE = 38,
	MSG_KEY_THERMOMETER = 39,
	MSG_KEY_TIMESTAMP = 40,
	MSG_KEY_UPTIME = 41,
	MSG_KEY_VENDOR_NAME = 42,
	MSG_KEY_VOLTAGE_LOAD = 43,
	MSG_KEY_VOLTAGE_REST = 44,
	MSG_KEY_W1_THERMOMETERS = 45,
	MSG_KEY_MEASUREMENTS_DIV = 46,
	MSG_KEY_MEASUREMENTS = 47,
	MSG_KEY_MEASUREMENTS_VAL = 48,
	MSG_KEY_BACKUP_STATE = 49,
	MSG_KEY_EVENTS = 50,
	MSG_KEY_LINE_VOLTAGE = 51,
	MSG_KEY_BATT_VOLTAGE = 52,
	MSG_KEY_BACKUP = 53,
	MSG_KEY_BACKUP_EVENTS = 54,
	MSG_KEY_SYSTEM = 55,
	MSG_KEY_RTD_THERMOMETER = 56,
	MSG_KEY_CHANNEL = 57,
	MSG_KEY_HYGRO_EVENTS = 58,
	MSG_KEY_TAMPER = 59,
	MSG_KEY_TAMPER_EVENTS = 60,
	MSG_KEY_TAMPER_STATE = 61,
	MSG_KEY_SOIL_SENSORS = 62,
	MSG_KEY_MOISTURE = 63,
};

#ifdef __cplusplus
}
#endif

#endif /* MSG_KEY_H_ */
