#ifndef MSG_KEY_H_
#define MSG_KEY_H_

/* This file has been generated using the script gen-msg-key.py */

#ifdef __cplusplus
extern "C" {
#endif

enum msg_key {
	MSG_KEY_ACCEL_X = 0,
	MSG_KEY_ACCEL_Y = 1,
	MSG_KEY_ACCEL_Z = 2,
	MSG_KEY_ACCELEROMETER = 3,
	MSG_KEY_ATTRIBUTE = 4,
	MSG_KEY_BAND = 5,
	MSG_KEY_BATTERY = 6,
	MSG_KEY_CID = 7,
	MSG_KEY_CURRENT_LOAD = 8,
	MSG_KEY_EARFCN = 9,
	MSG_KEY_ECL = 10,
	MSG_KEY_EEST = 11,
	MSG_KEY_FRAME = 12,
	MSG_KEY_FW_VERSION = 13,
	MSG_KEY_HUMIDITY = 14,
	MSG_KEY_HYGROMETER = 15,
	MSG_KEY_HW_REVISION = 16,
	MSG_KEY_HW_VARIANT = 17,
	MSG_KEY_IMEI = 18,
	MSG_KEY_IMSI = 19,
	MSG_KEY_NETWORK = 20,
	MSG_KEY_ORIENTATION = 21,
	MSG_KEY_PARAMETER = 22,
	MSG_KEY_PLMN = 23,
	MSG_KEY_PRODUCT_NAME = 24,
	MSG_KEY_PROTOCOL = 25,
	MSG_KEY_RSRP = 26,
	MSG_KEY_RSRQ = 27,
	MSG_KEY_SAMPLE_COUNT = 28,
	MSG_KEY_SEQUENCE = 29,
	MSG_KEY_SERIAL_NUMBER = 30,
	MSG_KEY_SNR = 31,
	MSG_KEY_STATE = 32,
	MSG_KEY_TEMPERATURE_AVG = 33,
	MSG_KEY_TEMPERATURE_MAX = 34,
	MSG_KEY_TEMPERATURE_MDN = 35,
	MSG_KEY_TEMPERATURE_MIN = 36,
	MSG_KEY_TEMPERATURE = 37,
	MSG_KEY_THERMOMETER = 38,
	MSG_KEY_TIMESTAMP = 39,
	MSG_KEY_UPTIME = 40,
	MSG_KEY_VENDOR_NAME = 41,
	MSG_KEY_VOLTAGE_LOAD = 42,
	MSG_KEY_VOLTAGE_REST = 43,
	MSG_KEY_W1_THERMOMETERS = 44,
	MSG_KEY_S1 = 45,
	MSG_KEY_CO2_CONCENTRATION = 46,
	MSG_KEY_PRESSURE = 47,
	MSG_KEY_ALTITUDE = 48,
	MSG_KEY_ILLUMINANCE = 49,
	MSG_KEY_PIR_COUNT = 50,
	MSG_KEY_BUTTON_COUNT = 51,
};

#ifdef __cplusplus
}
#endif

#endif /* MSG_KEY_H_ */
