#ifndef MSG_KEY_H_
#define MSG_KEY_H_

/* This file has been generated using the script gen-msg-key.py */

#ifdef __cplusplus
extern "C" {
#endif

enum msg_key {
	MSG_KEY_ACCELERATION_X = 0,
	MSG_KEY_ACCELERATION_Y = 1,
	MSG_KEY_ACCELERATION_Z = 2,
	MSG_KEY_ACCELEROMETER = 3,
	MSG_KEY_ALTITUDE = 4,
	MSG_KEY_ATTRIBUTE = 5,
	MSG_KEY_BAND = 6,
	MSG_KEY_CID = 7,
	MSG_KEY_CURRENT_LOAD = 8,
	MSG_KEY_EARFCN = 9,
	MSG_KEY_ECL = 10,
	MSG_KEY_EEST = 11,
	MSG_KEY_MESSAGE = 12,
	MSG_KEY_FW_NAME = 13,
	MSG_KEY_FW_VERSION = 14,
	MSG_KEY_HUMIDITY = 15,
	MSG_KEY_HYGROMETER = 16,
	MSG_KEY_HW_REVISION = 17,
	MSG_KEY_HW_VARIANT = 18,
	MSG_KEY_VERSION = 19,
	MSG_KEY_IMEI = 20,
	MSG_KEY_IMSI = 21,
	MSG_KEY_NETWORK = 22,
	MSG_KEY_ORIENTATION = 23,
	MSG_KEY_PARAMETER = 24,
	MSG_KEY_PLMN = 25,
	MSG_KEY_PRODUCT_NAME = 26,
	MSG_KEY_RSRP = 27,
	MSG_KEY_RSRQ = 28,
	MSG_KEY_SEQUENCE = 29,
	MSG_KEY_SERIAL_NUMBER = 30,
	MSG_KEY_SNR = 31,
	MSG_KEY_TEMPERATURE = 32,
	MSG_KEY_THERMOMETER = 33,
	MSG_KEY_TIMESTAMP = 34,
	MSG_KEY_UPTIME = 35,
	MSG_KEY_VENDOR_NAME = 36,
	MSG_KEY_VOLTAGE_LOAD = 37,
	MSG_KEY_VOLTAGE_REST = 38,
	MSG_KEY_W1_THERMOMETERS = 39,
	MSG_KEY_MEASUREMENTS_DIV = 40,
	MSG_KEY_MEASUREMENTS = 41,
	MSG_KEY_MEASUREMENTS_VAL = 42,
	MSG_KEY_MEASUREMENTS_VAL_DIV = 43,
	MSG_KEY_BACKUP_STATE = 44,
	MSG_KEY_EVENTS = 45,
	MSG_KEY_LINE_VOLTAGE = 46,
	MSG_KEY_BATT_VOLTAGE = 47,
	MSG_KEY_BACKUP = 48,
	MSG_KEY_BACKUP_EVENTS = 49,
	MSG_KEY_SYSTEM = 50,
	MSG_KEY_CHANNEL = 51,
	MSG_KEY_WEATHER_STATION = 52,
	MSG_KEY_WIND_SPEED = 53,
	MSG_KEY_WIND_DIRECTION = 54,
	MSG_KEY_RAINFALL = 55,
	MSG_KEY_BAROMETER = 56,
	MSG_KEY_PRESSURE = 57,
	MSG_KEY_SOIL_SENSORS = 58,
	MSG_KEY_MOISTURE = 59,
	MSG_KEY_RAINFALL_INTENSITY = 60,
	MSG_KEY_RAINFALL_TOTAL = 61,
	MSG_KEY_DEW_POINT = 62,
	MSG_KEY_ILLUMINANCE = 63,
};

#ifdef __cplusplus
}
#endif

#endif /* MSG_KEY_H_ */
