#ifndef MSG_KEY_H_
#define MSG_KEY_H_

/* This file has been generated using the script gen-msg-key.py */

#ifdef __cplusplus
extern "C" {
#endif

enum msg_key {
	MSG_KEY_ACCEL_X = 0,
	MSG_KEY_ACCEL_Y = 1,
	MSG_KEY_ACCEL_Z = 2,
	MSG_KEY_ACCELEROMETER = 3,
	MSG_KEY_ATTRIBUTE = 4,
	MSG_KEY_BAND = 5,
	MSG_KEY_BATTERY = 6,
	MSG_KEY_CHANNEL_1 = 7,
	MSG_KEY_CHANNEL_2 = 8,
	MSG_KEY_CHANNEL_3 = 9,
	MSG_KEY_CHANNEL_4 = 10,
	MSG_KEY_CHANNEL_5 = 11,
	MSG_KEY_CHANNEL_6 = 12,
	MSG_KEY_CHANNEL_7 = 13,
	MSG_KEY_CHANNEL_8 = 14,
	MSG_KEY_CID = 15,
	MSG_KEY_COUNTER = 16,
	MSG_KEY_CURRENT_LOAD = 17,
	MSG_KEY_EARFCN = 18,
	MSG_KEY_ECL = 19,
	MSG_KEY_EEST = 20,
	MSG_KEY_FRAME = 21,
	MSG_KEY_FW_VERSION = 22,
	MSG_KEY_HW_REVISION = 23,
	MSG_KEY_HW_VARIANT = 24,
	MSG_KEY_IMEI = 25,
	MSG_KEY_IMSI = 26,
	MSG_KEY_NETWORK = 27,
	MSG_KEY_ORIENTATION = 28,
	MSG_KEY_PARAMETER = 29,
	MSG_KEY_PLMN = 30,
	MSG_KEY_PRODUCT_NAME = 31,
	MSG_KEY_PROTOCOL = 32,
	MSG_KEY_RSRP = 33,
	MSG_KEY_RSRQ = 34,
	MSG_KEY_SEQUENCE = 35,
	MSG_KEY_SERIAL_NUMBER = 36,
	MSG_KEY_SNR = 37,
	MSG_KEY_STATE = 38,
	MSG_KEY_TEMPERATURE = 39,
	MSG_KEY_THERMOMETER = 40,
	MSG_KEY_TIMESTAMP = 41,
	MSG_KEY_UPTIME = 42,
	MSG_KEY_VENDOR_NAME = 43,
	MSG_KEY_VOLTAGE_LOAD = 44,
	MSG_KEY_VOLTAGE_REST = 45,
};

#ifdef __cplusplus
}
#endif

#endif /* MSG_KEY_H_ */
