@startuml

skin rose

title LTE State Diagram

(STATE_DISABLED)
(STATE_ERROR)
(STATE_BOOT)
(STATE_PREPARE)
(STATE_RESET_LOOP)
(STATE_RETRY_DELAY)
(STATE_ATTACH)
(STATE_OPEN_SOCKET)
(STATE_READY)
(STATE_SLEEP)
(STATE_WAKEUP)
(STATE_SEND)
(STATE_RECEIVE)
(STATE_CONEVAL)
(STATE_GNSS)

STATE_DISABLED --> STATE_BOOT: EVENT_ENABLE \n STATE_ERROR

STATE_ERROR --> STATE_BOOT: EVENT_TIMEOUT

STATE_BOOT --> STATE_PREPARE: EVENT_READY
STATE_BOOT --> STATE_ERROR: EVENT_TIMEOUT

STATE_PREPARE --> STATE_ATTACH: EVENT_SIMDETECTED
STATE_PREPARE --> STATE_ERROR: EVENT_TIMEOUT
STATE_PREPARE --> STATE_RESET_LOOP: EVENT_RESET_LOOP

STATE_RESET_LOOP --> STATE_ATTACH: EVENT_TIMEOUT (32min)
' STATE_RESET_LOOP --> STATE_ERROR: EVENT_ERROR

STATE_ATTACH --> STATE_OPEN_SOCKET: EVENT_REGISTERED
STATE_ATTACH --> STATE_RESET_LOOP: EVENT_RESET_LOOP
STATE_ATTACH --> STATE_RETRY_DELAY: EVENT_TIMEOUT
' STATE_ATTACH --> STATE_ERROR: EVENT_ERROR

STATE_RETRY_DELAY --> STATE_BOOT: EVENT_TIMEOUT

STATE_OPEN_SOCKET --> STATE_CONEVAL: EVENT_SOCKET_OPENED
STATE_OPEN_SOCKET --> STATE_ATTACH: EVENT_DEREGISTERED
' STATE_OPEN_SOCKET --> STATE_ERROR: EVENT_ERROR

STATE_CONEVAL --> STATE_READY

STATE_READY --> STATE_SEND : EVENT_SEND
STATE_READY --> STATE_SLEEP : EVENT_XMODMSLEEEP
STATE_READY --> STATE_ATTACH: EVENT_DEREGISTERED
STATE_READY --> STATE_GNSS: EVENT_XMODMSLEEEP

STATE_SLEEP --> STATE_WAKEUP : EVENT_SEND

STATE_WAKEUP --> STATE_READY : EVENT_READY
STATE_WAKEUP --> STATE_ERROR :  EVENT_TIMEOUT

STATE_SEND --> STATE_RECEIVE : EVENT_CSCON_1
STATE_SEND --> STATE_CONEVAL : EVENT_CSCON_1 (if not receive buffer)
STATE_SEND --> STATE_SEND: EVENT_TIMEOUT
STATE_SEND --> STATE_ATTACH: EVENT_DEREGISTERED

STATE_RECEIVE --> STATE_CONEVAL : EVENT_CSCON_0
STATE_RECEIVE --> STATE_ATTACH: EVENT_DEREGISTERED
STATE_RECEIVE --> STATE_SLEEP : EVENT_XMODMSLEEEP

STATE_GNSS --> STATE_READY : EVENT_SEND

@enduml
