#ifndef CHESTER_SUBSYS_CTR_SAT_ASTRONODE_S_H_
#define CHESTER_SUBSYS_CTR_SAT_ASTRONODE_S_H_

/* Zephyr includes */
#include <zephyr/sys/util.h>

#define ASTRONODE_S_CMD_CFG_W 0x05
#define ASTRONODE_S_CMD_CFG_R 0x15
#define ASTRONODE_S_CMD_WIF_W 0x06
#define ASTRONODE_S_CMD_PLD_E 0x25
#define ASTRONODE_S_CMD_PLD_D 0x26
#define ASTRONODE_S_CMD_PLD_F 0x27
#define ASTRONODE_S_CMD_SAK_R 0x45
#define ASTRONODE_S_CMD_SAK_C 0x46
#define ASTRONODE_S_CMD_CMD_R 0x47
#define ASTRONODE_S_CMD_CMD_C 0x48
#define ASTRONODE_S_CMD_RES_C 0x55
#define ASTRONODE_S_CMD_EVT_R 0x65

#define ASTRONODE_S_ANSWER_CODE(command_id) ((command_id) | 0x80)
#define ASTRONODE_S_ANSWER_ERROR	    0xFF

#define ASTRONODE_S_ERROR_CRC_NOT_VALID 0x0001
#define ASTRONODE_S_ERROR_DUPLICATE_ID	0x2511
#define ASTRONODE_S_ERROR_BUFFER_EMPTY	0x2601

#define ASTRONODE_S_START_BYTE 0x02
#define ASTRONODE_S_END_BYTE   0x03

#define ASTRONODE_MAX_RESET_WAKEUP_TIME_MSEC 400

#define ASTRONODE_S_CFG1_ACK_EN_MASK		BIT(0)
#define ASTRONODE_S_CFG1_ADD_GEO_MASK		BIT(1)
#define ASTRONODE_S_CFG1_EPHEMERIS_EN_MASK	BIT(2)
#define ASTRONODE_S_CFG1_DEEPSLEEP_EN_MASK	BIT(3)
#define ASTRONODE_S_CFG3_INT_ACK_EN_MASK	BIT(0)
#define ASTRONODE_S_CFG3_INT_RST_EN_MASK	BIT(1)
#define ASTRONODE_S_CFG3_INT_CMD_EN_MASK	BIT(2)
#define ASTRONODE_S_CFG3_INT_TX_PENDING_EN_MASK BIT(3)

#define ASTRONODE_S_CFG_RA_SIZE		   8
#define ASTRONODE_S_CFG_RA_PRODUCT_ID	   0
#define ASTRONODE_S_CFG_RA_HW_REV	   1
#define ASTRONODE_S_CFG_RA_FW_VER_MAJOR	   2
#define ASTRONODE_S_CFG_RA_FW_VER_MINOR	   3
#define ASTRONODE_S_CFG_RA_FW_VER_REVISION 4
#define ASTRONODE_S_CFG_RA_CFG1		   5
#define ASTRONODE_S_CFG_RA_CFG2		   6
#define ASTRONODE_S_CFG_RA_CFG3		   7

#define ASTRONODE_S_CFG_WR_SIZE 3
#define ASTRONODE_S_CFG_WR_CFG1 0
#define ASTRONODE_S_CFG_WR_CFG2 1
#define ASTRONODE_S_CFG_WR_CFG3 2

#define ASTRONODE_S_EVENT_SAT_ACK		   BIT(0)
#define ASTRONODE_S_EVENT_MODULE_RESET		   BIT(1)
#define ASTRONODE_S_EVENT_COMMAND_AVAILABLE	   BIT(2)
#define ASTRONODE_S_EVENT_MESSAGE_TRANSMIT_PENDING BIT(3)

#define ASTRONODE_S_WFI_WR_SIZE		 194
#define ASTRONODE_S_WFI_WR_SSID		 0
#define ASTRONODE_S_WFI_WR_SSID_SIZE	 33
#define ASTRONODE_S_WFI_WR_PASSWORD	 33
#define ASTRONODE_S_WFI_WR_PASSWORD_SIZE 64
#define ASTRONODE_S_WFI_WR_API_KEY	 97
#define ASTRONODE_S_WFI_WR_API_KEY_SIZE	 97

#define ASTRONODE_S_PLD_ER_SIZE	     162
#define ASTRONODE_S_PLD_ER_ID	     0
#define ASTRONODE_S_PLD_ER_DATA	     2
#define ASTRONODE_S_PLD_ER_DATA_SIZE 160

#define ASTRONODE_S_PLD_EA_SIZE 2
#define ASTRONODE_S_PLD_EA_ID	0

#define ASTRONODE_S_CMD_RA_SIZE		44
#define ASTRONODE_S_CMD_RA_CREATED_DATE 0
#define ASTRONODE_S_CMD_RA_PAYLOAD	4

#define ASTRONODE_S_ERR_ANSWER_SIZE	2
#define ASTRONODE_S_ERR_ANSWER_ERROR_ID 0

#endif /* CHESTER_SUBSYS_CTR_SAT_ASTRONODE_S_H_ */
