version: 1
variants:
- name: CHESTER Control
  fw_bundle: com.hardwario.chester.app.control
  fw_name: hio-chester-control
  fw_version: v3.0.0
project:
  variant: Control
  company: 2024 HARDWARIO a.s.
  license: 'SPDX-License-Identifier: LicenseRef-HARDWARIO-5-Clause'
  fw_name: CHESTER Control
  fw_bundle: com.hardwario.chester.app.control
  fw_version: v3.0.0
features:
- subsystem-accel
- subsystem-adc
- subsystem-batt
- subsystem-bluetooth
- subsystem-ble-tag
- subsystem-bt-observer
- subsystem-bt-filter-accept-list
- subsystem-buf
- subsystem-button
- subsystem-config
- subsystem-cloud
- subsystem-defaults
- subsystem-edge
- subsystem-info
- subsystem-led
- subsystem-log
- subsystem-rtc
- subsystem-shell
- subsystem-therm
- subsystem-wdog
- subsystem-entropy-generator
- subsystem-tinycrypt
- subsystem-tinycrypt-sha256
- subsystem-zcbor
- subsystem-lte-v2
- subsystem-ds18b20
- hardware-chester-x0-a
- hardware-chester-x4-b
#- hardware-chester-x0-a
#- hardware-chester-s2
#- hardware-chester-z
#- hardware-chester-x4-a
#- hardware-chester-x9-a
#- hardware-chester-x9-b
parameters:
- name: interval-report
  type: int
  min: 30
  max: 86400
  default: 1800
  help: 'Get/Set report interval in seconds'
- name: interval-poll
  type: int
  min: 0
  max: 86400
  default: 0
  help: 'Get/Set poll interval in seconds'
- name: event-report-delay
  type: int
  min: 1
  max: 86400
  default: 5
  help: 'Get/Set event report delay in seconds'
  depends_on:  defined(FEATURE_HARDWARE_CHESTER_Z) || defined(FEATURE_HARDWARE_CHESTER_X0_A)
- name: event-report-rate
  type: int
  min: 1
  max: 3600
  default: 30
  help: 'Get/Set event report rate in reports per hour'
  depends_on: defined(FEATURE_HARDWARE_CHESTER_Z) || defined(FEATURE_HARDWARE_CHESTER_X0_A)
- name: backup-report-connected
  type: bool
  default: true
  help: 'Get/Set report when backup is active'
  depends_on: defined(FEATURE_HARDWARE_CHESTER_Z)
- name: backup-report-disconnected
  type: bool
  default: true
  help: 'Get/Set report when backup is inactive'
  depends_on: defined(FEATURE_HARDWARE_CHESTER_Z)
- name: channel-mode-{}
  type: enum
  valueset:
    - trigger
    - counter
    - voltage
    - current
  depends_on: defined(FEATURE_HARDWARE_CHESTER_X0_A)
- name: input-type
  type: enum
  valueset:
    - npn
    - pnp
  related:
    - name: trigger
      default: npn
      help: 'Get/Set trigger input type'
    - name: counter
      default: npn
      help: 'Get/Set counter input type'
  depends_on: defined(FEATURE_HARDWARE_CHESTER_X0_A)
- name: trigger-duration-active
  type: int
  min: 0
  max: 60000
  default: 100
  help: 'Get/Set event active duration in milliseconds'
  depends_on: defined(FEATURE_HARDWARE_CHESTER_X0_A)
- name: trigger-duration-inactive
  type: int
  min: 0
  max: 60000
  default: 100
  help: 'Get/Set event inactive duration in milliseconds'
  depends_on: defined(FEATURE_HARDWARE_CHESTER_X0_A)
- name: trigger-cooldown-time
  type: int
  min: 0
  max: 60000
  default: 10
  help: 'Get/Set trigger cooldown time in milliseconds'
  depends_on: defined(FEATURE_HARDWARE_CHESTER_X0_A)
- name: trigger-report-active
  type: bool
  default: false
  help: 'Get/Set report when trigger is active'
  depends_on: defined(FEATURE_HARDWARE_CHESTER_X0_A)
- name: trigger-report-inactive
  type: bool
  default: false
  help: 'Get/Set report when trigger is inactive'
  depends_on: defined(FEATURE_HARDWARE_CHESTER_X0_A)
- name: counter-interval-aggreg
  type: int
  min: 1
  max: 86400
  default: 300
  help: 'Get/Set counter aggregation interval in seconds'
  depends_on: defined(FEATURE_HARDWARE_CHESTER_X0_A)
- name: counter-duration-active
  type: int
  min: -0
  max: 60000
  default: 2
  help: 'Get/Set event active duration in milliseconds'
  depends_on: defined(FEATURE_HARDWARE_CHESTER_X0_A)
- name: counter-duration-inactive
  type: int
  min: 0
  max: 60000
  default: 2
  help: 'Get/Set event inactive duration in milliseconds'
  depends_on: defined(FEATURE_HARDWARE_CHESTER_X0_A)
- name: counter-cooldown-time
  type: int
  min: 0
  max: 60000
  default: 10
  help: 'Get/Set counter cooldown time in milliseconds'
  depends_on: defined(FEATURE_HARDWARE_CHESTER_X0_A)
- name: analog-interval-sample
  type: int
  min: 1
  max: 86400
  default: 60
  help: 'Get/Set analog sample interval in seconds'
  depends_on: defined(FEATURE_HARDWARE_CHESTER_X0_A)
- name: analog-interval-aggreg
  type: int
  min: 1
  max: 86400
  default: 300
  help: 'Get/Set analog aggregation interval in seconds'
  depends_on: defined(FEATURE_HARDWARE_CHESTER_X0_A)
- name: hygro-interval-sample
  type: int
  min: 1
  max: 86400
  default: 60
  help: 'Get/Set hygro sample interval in seconds'
  depends_on: defined(FEATURE_HARDWARE_CHESTER_S2)
- name: hygro-interval-aggreg
  type: int
  min: 1
  max: 86400
  default: 300
  help: 'Get/Set hygro aggreg interval in seconds'
  depends_on: defined(FEATURE_HARDWARE_CHESTER_S2)
- name: w1-therm-interval-sample
  type: int
  min: 1
  max: 86400
  default: 60
  help: 'Get/Set ds18b20 sample interval in seconds'
  depends_on: defined(FEATURE_SUBSYSTEM_DS18B20)
- name: w1-therm-interval-aggreg
  type: int
  min: 1
  max: 86400
  default: 300
  help: 'Get/Set ds18b20 aggreg interval in seconds '
  depends_on: defined(FEATURE_SUBSYSTEM_DS18B20)
commands:
- name: sample
  callback: app_work_sample()
  help: 'Sample immediately.'
- name: send
  callback: app_work_send()
  help: 'Send data immediately.'
- name: poll
  callback: app_work_poll()
  help: 'Poll cloud immediately.'
extras:
- CONFIG_ADC_SHELL=n
- CONFIG_SYS_HEAP_RUNTIME_STATS=y
- CONFIG_HEAP_MEM_POOL_SIZE=32768
- CONFIG_ADC_TLA2021_INIT_PRIORITY=60
