/*
 * Copyright (c) 2023 HARDWARIO a.s.
 *
 * SPDX-License-Identifier: LicenseRef-HARDWARIO-5-Clause
 */

#ifndef MSG_KEY_H_
#define MSG_KEY_H_

/* This file has been generated using the script gen-msg-key.py */

#ifdef __cplusplus
extern "C" {
#endif

enum msg_key {
	MSG_KEY_ACCEL_X = 0,
	MSG_KEY_ACCEL_Y = 1,
	MSG_KEY_ACCEL_Z = 2,
	MSG_KEY_ACCELEROMETER = 3,
	MSG_KEY_ATTRIBUTE = 4,
	MSG_KEY_BAND = 5,
	MSG_KEY_BATTERY = 6,
	MSG_KEY_CHANNEL_1_TOTAL = 7,
	MSG_KEY_CHANNEL_1_DELTA = 8,
	MSG_KEY_CHANNEL_2_TOTAL = 9,
	MSG_KEY_CHANNEL_2_DELTA = 10,
	MSG_KEY_CHANNEL_3_TOTAL = 11,
	MSG_KEY_CHANNEL_3_DELTA = 12,
	MSG_KEY_CHANNEL_4_TOTAL = 13,
	MSG_KEY_CHANNEL_4_DELTA = 14,
	MSG_KEY_CHANNEL_5_TOTAL = 15,
	MSG_KEY_CHANNEL_5_DELTA = 16,
	MSG_KEY_CHANNEL_6_TOTAL = 17,
	MSG_KEY_CHANNEL_6_DELTA = 18,
	MSG_KEY_CHANNEL_7_TOTAL = 19,
	MSG_KEY_CHANNEL_7_DELTA = 20,
	MSG_KEY_CHANNEL_8_TOTAL = 21,
	MSG_KEY_CHANNEL_8_DELTA = 22,
	MSG_KEY_CID = 23,
	MSG_KEY_COUNTER = 24,
	MSG_KEY_CURRENT_LOAD = 25,
	MSG_KEY_EARFCN = 26,
	MSG_KEY_ECL = 27,
	MSG_KEY_EEST = 28,
	MSG_KEY_FRAME = 29,
	MSG_KEY_FW_VERSION = 30,
	MSG_KEY_HW_REVISION = 31,
	MSG_KEY_HW_VARIANT = 32,
	MSG_KEY_IMEI = 33,
	MSG_KEY_IMSI = 34,
	MSG_KEY_NETWORK = 35,
	MSG_KEY_ORIENTATION = 36,
	MSG_KEY_PARAMETER = 37,
	MSG_KEY_PLMN = 38,
	MSG_KEY_PRODUCT_NAME = 39,
	MSG_KEY_PROTOCOL = 40,
	MSG_KEY_RSRP = 41,
	MSG_KEY_RSRQ = 42,
	MSG_KEY_SEQUENCE = 43,
	MSG_KEY_SERIAL_NUMBER = 44,
	MSG_KEY_SNR = 45,
	MSG_KEY_STATE = 46,
	MSG_KEY_TEMPERATURE = 47,
	MSG_KEY_THERMOMETER = 48,
	MSG_KEY_TIMESTAMP = 49,
	MSG_KEY_UPTIME = 50,
	MSG_KEY_VENDOR_NAME = 51,
	MSG_KEY_VOLTAGE_LOAD = 52,
	MSG_KEY_VOLTAGE_REST = 53,
	MSG_KEY_BACKUP = 54,
	MSG_KEY_LINE_VOLTAGE = 55,
	MSG_KEY_BATT_VOLTAGE = 56,
	MSG_KEY_BACKUP_STATE = 57,
	MSG_KEY_BACKUP_EVENTS = 58,
	MSG_KEY_TAMPER = 59,
	MSG_KEY_TAMPER_EVENTS = 60,
	MSG_KEY_TAMPER_STATE = 61,
};

#ifdef __cplusplus
}
#endif

#endif /* MSG_KEY_H_ */
